--
-- Tables for use with Eclipse Project: RESTfulExampleJAX-RS
-- Reference URL: http://blog.bdoughan.com/2010/08/creating-restful-web-service-part-15.html
--

--
-- Table: CUSTOMER
--
CREATE TABLE IF NOT EXISTS `CUSTOMER` 
( `ID` INT NOT NULL , 
  `FIRST_NAME` VARCHAR(50) , 
  `LAST_NAME` VARCHAR(50) ,
  CONSTRAINT `CUSTOMER_PK` PRIMARY KEY (`ID`)   
);

--
-- Table: ADDRESS
--
CREATE TABLE IF NOT EXISTS `ADDRESS`
 ( `ID` INT NOT NULL, 
 `STREET` VARCHAR(50), 
 `CITY` VARCHAR(50),
 CONSTRAINT `ADDRESS_PK` PRIMARY KEY (`ID`), 
 CONSTRAINT `ADDRESS_FK` FOREIGN KEY (`ID`)
 	REFERENCES `CUSTOMER` (`ID`)
 );
 
--
-- Table: PHONE_NUMBER
--
CREATE TABLE IF NOT EXISTS `PHONE_NUMBER`
 ( `ID` INT NOT NULL , 
 `TYPE` VARCHAR(50), 
 `NUM` VARCHAR(50), 
 `ID_CUSTOMER` INT, 
 CONSTRAINT `PHONE_NUMBER_PK` PRIMARY KEY (`ID`) , 
 CONSTRAINT `PHONE_NUMBER_FK` FOREIGN KEY (`ID_CUSTOMER`)
 	REFERENCES `CUSTOMER` (`ID`) 
 );
