INSERT INTO customer (ID, FIRST_NAME, LAST_NAME) VALUES (59, 'Angela', 'Jenkins')
INSERT INTO customer (ID, FIRST_NAME, LAST_NAME) VALUES (101, 'Mrs.', 'NO-PHONES')
INSERT INTO customer (ID, FIRST_NAME, LAST_NAME) VALUES (151, 'Frank', 'Zappa')
INSERT INTO customer (ID, FIRST_NAME, LAST_NAME) VALUES (201, 'Jane', 'Smith')
INSERT INTO customer (ID, FIRST_NAME, LAST_NAME) VALUES (204, 'John', 'Doe')

INSERT INTO address (ID, CITY, STREET, ID_CUSTOMER) VALUES (60, 'SECOND-CITY', '123 Your Street', 59)
INSERT INTO address (ID, CITY, STREET, ID_CUSTOMER) VALUES (102, 'Sacramento', '123 Your Street', 101)
INSERT INTO address (ID, CITY, STREET, ID_CUSTOMER) VALUES (152, 'Sacramento', '123 ANY CIRCLE', 151)
INSERT INTO address (ID, CITY, STREET, ID_CUSTOMER) VALUES (202, 'Roseville', '123 Your Street', 201)
INSERT INTO address (ID, CITY, STREET, ID_CUSTOMER) VALUES (205, 'Sacramento', '123 Your Street', 204)

INSERT INTO phone_number (ID, NUM, TYPE, ID_CUSTOMER) VALUES (61, '916-321-1212', 'Work', 59)
INSERT INTO phone_number (ID, NUM, TYPE, ID_CUSTOMER) VALUES (153, '800-567-1525 x221', 'TOLL-FREE', 151)
INSERT INTO phone_number (ID, NUM, TYPE, ID_CUSTOMER) VALUES (154, '916-555-5656', 'Work', 151)
INSERT INTO phone_number (ID, NUM, TYPE, ID_CUSTOMER) VALUES (203, '916-321-1212', 'Work', 201)
INSERT INTO phone_number (ID, NUM, TYPE, ID_CUSTOMER) VALUES (206, '916-321-1111', 'Work', 204)

INSERT INTO sequence (SEQ_NAME, SEQ_COUNT) VALUES ('SEQ_GEN', 250)
